# Generated by Django 5.1.7 on 2025-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='vector_collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
